# Generated by Django 3.1 on 2022-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20220516_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.URLField(blank=True, max_length=5000),
        ),
    ]
